import React from 'react';

export const translations = {
  en: {
    appName: 'NutriShield Mother Care',
    tagline: 'AI-Powered Maternal Nutrition & Anemia Alert System',
    selectLanguage: 'Select Your Language',
    continue: 'Continue',
    back: 'Back',
    next: 'Next',
    save: 'Save',
    submit: 'Submit',
    yes: 'Yes',
    no: 'No',
    name: 'Full Name',
    age: 'Age',
    gender: 'Gender',
    occupation: 'Occupation',
    pregnancyType: 'Pregnancy',
    firstPregnancy: 'First Pregnancy',
    multiplePregnancy: 'Multiple Pregnancies',
    permissions: 'App Permissions',
    permissionsDesc: 'We need these permissions to provide accurate health analysis',
    camera: 'Camera Access',
    location: 'Location Access',
    files: 'File Access',
    notifications: 'Notifications',
    grantAll: 'Grant All Permissions',
    bloodTest: 'Do you have a blood test report?',
    uploadReport: 'Upload Blood Test Image',
    symptoms: 'Select Your Symptoms',
    analyzeReport: 'Analyze Report',
    analyzing: 'Analyzing...',
    anemic: 'Anemic',
    normal: 'Normal',
    dietPlan: 'Your Personalized Diet Plan',
    dashboard: 'Health Dashboard',
  },
  hi: {
    appName: 'न्यूट्रीशील्ड मदर केयर',
    tagline: 'AI-संचालित मातृ पोषण और एनीमिया अलर्ट सिस्टम',
    selectLanguage: 'अपनी भाषा चुनें',
    continue: 'जारी रखें',
    back: 'वापस',
    next: 'अगला',
    save: 'सहेजें',
    submit: 'जमा करें',
    yes: 'हाँ',
    no: 'नहीं',
    name: 'पूರಾ नाम',
    age: 'आयु',
    gender: 'लिंग',
    occupation: 'व्यवसाय',
    pregnancyType: 'गर्भावस्था',
    firstPregnancy: 'पहली गर्भावस्था',
    multiplePregnancy: 'एकाधिक गर्भावस्था',
    permissions: 'ऐप अनुमतियाँ',
    permissionsDesc: 'सटीಕ स्वास्थ्य विश्लेषण के लिए इन अनुमतियों की आवश्यकता है',
    camera: 'कैमरा एक्सेस',
    location: 'स्थान एक्सेस',
    files: 'फ़ाइल एक्सेस',
    notifications: 'सूचनाएं',
    grantAll: 'सभी अनुमतियाँ दें',
    bloodTest: 'क्या आपके पास रक्त परीक्षण रिपोर्ट है?',
    uploadReport: 'रक्त परीक्षण छवि अपलोड करें',
    symptoms: 'अपने लक्षण चुनें',
    analyzeReport: 'रिपोर्ट विश्लेषण करें',
    analyzing: 'विश्लेषण हो रहा है...',
    anemic: 'एनीमिक',
    normal: 'सामान्य',
    dietPlan: 'आपकी व्यक्तिगत आहार योजना',
    dashboard: 'स्वास्थ्य डैशबोर्ड',
  },
  kn: {
    appName: 'ನ್ಯೂಟ್ರಿಶೀಲ್ಡ್ ಮದರ್ ಕೇರ್',
    tagline: 'AI-ಚಾಲಿತ ತಾಯ್ತನ ಪೋಷಣೆ ಮತ್ತು ರಕ್ತಹೀನತೆ ಎಚ್ಚರಿಕೆ ವ್ಯವಸ್ಥೆ',
    selectLanguage: 'ನಿಮ್ಮ ಭಾಷೆ ಆರಿಸಿ',
    continue: 'ಮುಂದುವರಿಸಿ',
    back: 'ಹಿಂದೆ',
    next: 'ಮುಂದೆ',
    save: 'ಉಳಿಸಿ',
    submit: 'ಸಲ್ಲಿಸಿ',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    name: 'ಪೂರ್ಣ ಹೆಸರು',
    age: 'ವಯಸ್ಸು',
    gender: 'ಲಿಂಗ',
    occupation: 'ವೃತ್ತಿ',
    pregnancyType: 'ಗರ್ಭಧಾರಣೆ',
    firstPregnancy: 'ಮೊದಲ ಗರ್ಭಧಾರಣೆ',
    multiplePregnancy: 'ಬಹು ಗರ್ಭಧಾರಣೆ',
    permissions: 'ಅಪ್ಲಿಕೇಶನ್ ಅನುಮತಿಗಳು',
    permissionsDesc: 'ನಿಖರ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಈ ಅನುಮತಿಗಳು ಬೇಕು',
    camera: 'ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶ',
    location: 'ಸ್ಥಳ ಪ್ರವೇಶ',
    files: 'ಫೈಲ್ ಪ್ರವೇಶ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    grantAll: 'ಎಲ್ಲಾ ಅನುಮತಿಗಳನ್ನು ನೀಡಿ',
    bloodTest: 'ನಿಮ್ಮ ಬಳಿ ರಕ್ತ ಪರೀಕ್ಷಾ ವರದಿ ಇದೆಯೇ?',
    uploadReport: 'ರಕ್ತ ಪರೀಕ್ಷೆ ಚಿತ್ರ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    symptoms: 'ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಆರಿಸಿ',
    analyzeReport: 'ವರದಿ ವಿಶ್ಲೇಷಿಸಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    anemic: 'ರಕ್ತಹೀನ',
    normal: 'ಸಾಮಾನ್ಯ',
    dietPlan: 'ನಿಮ್ಮ ವ್ಯಕ್ತಿಗತ ಆಹಾರ ಯೋಜನೆ',
    dashboard: 'ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  }
};

export const AppContext = React.createContext(null);
